2019-08-28-16:30:07.419 DEBUG [db]  New LevelDbDataSource: blocks
2019-08-28-16:30:07.435 DEBUG [db]  ~> LevelDbDataSource.init(): blocks
2019-08-28-16:30:07.436 DEBUG [db]  Opening database
2019-08-28-16:30:07.444 ERROR [db]  /database
java.nio.file.AccessDeniedException: /database
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.ethereum.datasource.LevelDbDataSource.init(LevelDbDataSource.java:98)
	at co.rsk.RskContext.makeDataSource(RskContext.java:1469)
	at co.rsk.core.db.bootstrap.FileExporter.main(FileExporter.java:49)
2019-08-28-16:30:07.444 ERROR [panic]  leveldb: /database
2019-08-28-16:30:07.444 ERROR [panic]  Stack Trace:
java.lang.Throwable: null
	at co.rsk.panic.PanicProcessor.panic(PanicProcessor.java:33)
	at org.ethereum.datasource.LevelDbDataSource.init(LevelDbDataSource.java:106)
	at co.rsk.RskContext.makeDataSource(RskContext.java:1469)
	at co.rsk.core.db.bootstrap.FileExporter.main(FileExporter.java:49)
